import React from 'react';

export default React.createContext({
  colors: Object,
  user: Object,
  isBoard: Boolean,
  selectedContact: String,
  inputFeilds: {},
  errorHandler: {},
  _toggleError: () => {},
  _setDialog: () => {},
  _onChange: () => {},
  _confirmPhone: () => {},
  _confirmSelected: () => {},
  _cangeUserState: () => {},
  _routeToPage: () => {},
  _applyForLoan: () => {},
  _handleRegister: () => {},
  _goBack: () => {},
  _confirmPaymentMethod: () => {},
  _verifyPayment: () => {},
  _autoVerifyPay: () => {},
  _bindPaymentMethod: () => {},
  _handleLoan1: () => {},
  _handleCheck: () => {},
  _getLoan: () => {},
  _resetLoanStatus: () => {},
  _loanDetails: () => {},
  _logout: () => {},
  _handleRepay: () => {},
  _applyExt: () => {},
  _getContacts: () => {},
  _getLoc: () => {},
});
